"""Added status to vehicle

Revision ID: 033ab6802599
Revises: 556334da5ce4
Create Date: 2026-09-23 17:51:03.325496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '033ab6802599'
down_revision: Union[str, Sequence[str], None] = '556334da5ce4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('research_status', sa.String(), nullable=False), schema='vehicle')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'research_status', schema='vehicle')
    # ### end Alembic commands ###
