"""Added tires to spec.

Revision ID: 2fc71dc08970
Revises: 83f2180c33d9
Create Date: 2026-09-24 16:58:08.003824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fc71dc08970'
down_revision: Union[str, Sequence[str], None] = '83f2180c33d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle_spec', sa.Column('stock_tire_class', sa.Integer(), nullable=True), schema='vehicle')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicle_spec', 'stock_tire_class', schema='vehicle')
    # ### end Alembic commands ###
