"""update metadata models

Revision ID: 556334da5ce4
Revises: e360313204b5
Create Date: 2026-09-23 17:22:32.738359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '556334da5ce4'
down_revision: Union[str, Sequence[str], None] = 'e360313204b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vehicle_specs_metadata', 'source_url',
               existing_type=sa.VARCHAR(),
               nullable=True,
               schema='vehicle')
    op.alter_column('vehicle_specs_metadata', 'confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               nullable=True,
               schema='vehicle')
    op.alter_column('vehicle_specs_metadata', 'date_set',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               schema='vehicle')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vehicle_specs_metadata', 'date_set',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               schema='vehicle')
    op.alter_column('vehicle_specs_metadata', 'confidence',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               schema='vehicle')
    op.alter_column('vehicle_specs_metadata', 'source_url',
               existing_type=sa.VARCHAR(),
               nullable=False,
               schema='vehicle')
    # ### end Alembic commands ###
