"""Changed year to a range

Revision ID: 83f2180c33d9
Revises: 033ab6802599
Create Date: 2026-09-24 00:18:01.465817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83f2180c33d9'
down_revision: Union[str, Sequence[str], None] = '033ab6802599'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('model_year_start', sa.Integer(), nullable=False), schema='vehicle')
    op.add_column('vehicles', sa.Column('model_year_end', sa.Integer(), nullable=False), schema='vehicle')
    op.drop_constraint(op.f('uq_vehicle_identity'), 'vehicles', schema='vehicle', type_='unique')
    op.create_unique_constraint('uq_vehicle_identity', 'vehicles', ['make', 'model', 'model_year_start', 'model_year_end', 'trim'], schema='vehicle')
    op.drop_column('vehicles', 'model_year', schema='vehicle')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('model_year', sa.INTEGER(), autoincrement=False, nullable=False), schema='vehicle')
    op.drop_constraint('uq_vehicle_identity', 'vehicles', schema='vehicle', type_='unique')
    op.create_unique_constraint(op.f('uq_vehicle_identity'), 'vehicles', ['make', 'model', 'model_year', 'trim'], schema='vehicle', postgresql_nulls_not_distinct=False)
    op.drop_column('vehicles', 'model_year_end', schema='vehicle')
    op.drop_column('vehicles', 'model_year_start', schema='vehicle')
    # ### end Alembic commands ###
