"""add vehicle dimensions and weight

Revision ID: e257427ae0f7
Revises: 90fe42cdac25
Create Date: 2026-09-22 19:42:52.695418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e257427ae0f7'
down_revision: Union[str, Sequence[str], None] = '90fe42cdac25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE SCHEMA IF NOT EXISTS vehicle")
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('make', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('width_mm', sa.Integer(), nullable=True),
    sa.Column('length_mm', sa.Integer(), nullable=True),
    sa.Column('height_mm', sa.Integer(), nullable=True),
    sa.Column('curb_weight_kg', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='vehicle'
    )
    op.drop_table('vehicles')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('make', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('model', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('vehicles_pkey'))
    )
    op.drop_table('vehicles', schema='vehicle')
    # ### end Alembic commands ###
