"""add vehicle specs and metadata

Revision ID: e360313204b5
Revises: e257427ae0f7
Create Date: 2026-09-23 11:44:36.944581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e360313204b5'
down_revision: Union[str, Sequence[str], None] = 'e257427ae0f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicle_spec',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('width_mm', sa.Integer(), nullable=True),
    sa.Column('length_mm', sa.Integer(), nullable=True),
    sa.Column('height_mm', sa.Integer(), nullable=True),
    sa.Column('curb_weight_kg', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.vehicles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vehicle_id'),
    schema='vehicle'
    )
    op.create_table('vehicle_specs_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('specs_id', sa.Integer(), nullable=False),
    sa.Column('variable', sa.String(), nullable=False),
    sa.Column('date_set', sa.DateTime(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['specs_id'], ['vehicle.vehicle_spec.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='vehicle'
    )
    op.add_column('vehicles', sa.Column('model_year', sa.Integer(), nullable=False), schema='vehicle')
    op.add_column('vehicles', sa.Column('trim', sa.String(), nullable=True), schema='vehicle')
    op.create_unique_constraint('uq_vehicle_identity', 'vehicles', ['make', 'model', 'model_year', 'trim'], schema='vehicle')
    op.drop_column('vehicles', 'length_mm', schema='vehicle')
    op.drop_column('vehicles', 'curb_weight_kg', schema='vehicle')
    op.drop_column('vehicles', 'width_mm', schema='vehicle')
    op.drop_column('vehicles', 'height_mm', schema='vehicle')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('height_mm', sa.INTEGER(), autoincrement=False, nullable=True), schema='vehicle')
    op.add_column('vehicles', sa.Column('width_mm', sa.INTEGER(), autoincrement=False, nullable=True), schema='vehicle')
    op.add_column('vehicles', sa.Column('curb_weight_kg', sa.INTEGER(), autoincrement=False, nullable=True), schema='vehicle')
    op.add_column('vehicles', sa.Column('length_mm', sa.INTEGER(), autoincrement=False, nullable=True), schema='vehicle')
    op.drop_constraint('uq_vehicle_identity', 'vehicles', schema='vehicle', type_='unique')
    op.drop_column('vehicles', 'trim', schema='vehicle')
    op.drop_column('vehicles', 'model_year', schema='vehicle')
    op.drop_table('vehicle_specs_metadata', schema='vehicle')
    op.drop_table('vehicle_spec', schema='vehicle')
    # ### end Alembic commands ###
